### PR TITLE
added repositery and dao classes along with annotations

### PR DESCRIPTION
**Pull request by RajBala-thakur**

### CODE REVIEW

**Review by suhassg25 — APPROVED** [review]
nothing changes are needed, i am approving.

**Review by suhassg25 — APPROVED** [review]
nothing changes are required i am approving

**Review by suhassg25 — APPROVED** [review]

**Review by kumarrishabh96 — APPROVED** [review]
no changes required

**Review by kiranwannerkar — APPROVED** [review]
code is ok

**Pull request merged**
